workspace:
  base: /root

pipeline:
  clone_target_repo:
    image: buildpack-deps:16.04-scm
    environment:
      - GH_TOKEN=$$GH_TOKEN
    commands:
      - pwd
      - git --version
      - (ls | grep --silent target) || git clone https://$GH_TOKEN@github.com/`cat REPOSITORY`.git target
      - cd target && ../verify.bash
    when:
      branches:
        exclude: [ ci ]
