---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 2

steps:
- name: check answer
  image: buildpack-deps:16.04-scm
  commands:
  - pwd
  - "export PATH=$${PATH}:`pwd`/bin"
  - "rm -rf target && git clone https://$GH_TOKEN@github.com/`cat REPOSITORY`.git target"
  - "cd target && ../verify.bash"
  environment:
    GH_TOKEN:
      from_secret: github_token
  when:
    branch:
      exclude:
      - ci
    event:
    - push
